---
- name: sysdig | setup yum
  include_vars: yum.yml

- yum_repository:
    name: Sysdig
    description: "sysdig - $basearch"
    baseurl: "{{ sysdig_repo }}"
    enabled: "{{ sysdig_repo_enabled }}"
    gpgkey: "{{ sysdig_repo_gpgkey_url }}"
    gpgcheck: "{{ sysdig_repo_gpgcheck }}"
    sslverify: "{{ sysdig_repo_ssl_verify }}"
  when: sysdig_repo_enabled == True

